#!/bin/bash
mkdir test2
cd test2
mkdir  2
cd  2
cp /home/lakelandcsi/code/test/usefulScripts/ftpArchives/test1/2/* .
cd ..
mkdir  3
cd  3
cp /home/lakelandcsi/code/test/usefulScripts/ftpArchives/test1/3/* .
cd ..
mkdir  1
cd  1
mkdir  2
cd  2
cp /home/lakelandcsi/code/test/usefulScripts/ftpArchives/test1/1/2/* .
cd ..
mkdir  1
cd  1
cp /home/lakelandcsi/code/test/usefulScripts/ftpArchives/test1/1/1/* .
cd ..
cp /home/lakelandcsi/code/test/usefulScripts/ftpArchives/test1/1/* .
cd ..
cp /home/lakelandcsi/code/test/usefulScripts/ftpArchives/test1/* .
cd ..
