#!/bin/bash
exec < "PLC_Logic.csv"

echo '{|border = "1" style="wikitable"'
echo "|+ Valve Positions"
read line
echo $line | sed -e 's/^/!/g' | sed -e 's/,/||/g'




while read line
do
	IFS=',' read -r first rest <<< "$line"
	echo "|-"
	echo "!"$first
	rest=$(echo $rest | sed -e 's/,/||/g')
	echo "|"$rest
done

echo "|}"
